# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa86876c4ef16e78793a0d6e3126bea6fda50b2cb9b3679c481b0495c76a0df54fc52824dac27f26e453526ff0363a126833da1abeb2bd4e419e83e761acad35

test:
  secret_key_base: 01cef531cd760ff5629020f47f93f53b8f8f4ef008cebc82caf4e3df9e76ba1692e08260634d9814425825408849d3d652a36c26b4f483af4241addd9c8549d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>